apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notifiarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Image updater configuration
    argocd-image-updater.argoproj.io/image-list: notifiarr=golift/notifiarr
    argocd-image-updater.argoproj.io/notifiarr.update-strategy: semver
    argocd-image-updater.argoproj.io/notifiarr.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/Gauransh-Homelab/Homelab.git
    targetRevision: main
    path: kubernetes/arr-stack
    directory:
      include: "notifiarr-deployment.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: arr-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m