apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpn-group
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Image updater configuration for multiple images
    argocd-image-updater.argoproj.io/image-list: |
      gluetun=qmcgaw/gluetun:~v3,
      qbittorrent=lscr.io/linuxserver/qbittorrent:~4.6,
      nzbget=lscr.io/linuxserver/nzbget
    argocd-image-updater.argoproj.io/gluetun.update-strategy: semver
    argocd-image-updater.argoproj.io/qbittorrent.update-strategy: semver
    argocd-image-updater.argoproj.io/nzbget.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/Gauransh-Homelab/Homelab.git
    targetRevision: main
    path: kubernetes/arr-stack
    directory:
      include: "{vpn-group-deployment.yaml,vpn-group-service.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: arr-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m