apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-key
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:Gauransh-Homelab/Homelab.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # YOUR SSH PRIVATE KEY HERE
    -----END OPENSSH PRIVATE KEY-----