apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-duckdns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: gauranshmathur1999@gmail.com
    privateKeySecretRef:
      name: letsencrypt-duckdns-private-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.duckdns.org
            solverName: duckdns
            config:
              token:
                secretKeyRef:
                  name: dns-secrets
                  key: duckdns-token
                  namespace: traefik

