---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: botkube-communications
  namespace: default
spec:
  encryptedData:
    comm_config.yaml: AgB69IrpwrvZUkDI4kMqxBafrJ+vLzAM99m9M+vuNou4h4+BD2EuUwlSOODBlIaI8m/7E5RXMPXZXFE2dVKq0G+ielBOl9UejWJQSeSmKVbfOnXBjB7LUzLwZMBoHSGN2m+AzgPYswhH4Xo6Bq+BETTG4jLlVEX2Gy/E8DWOqDrr+DDdBiYwdDg/Z23FTIO4eRZ0N8dqV4DKYB0k8d66lawtVcBa6WW45+ePf1VZQ1wirXoi5vrwDvc3DAh/FiGhyh8BkcFwX2Cx/1pJFU/NNGFhQGbmwASJLw/jxPMpDVllQH3EWYnELGxHW1J+145KNutkTeZsnQIPrbdd1VQ9C1WXEEqMJaRLOGSc6CiDPAKtWwLvYI29KVnTC9DynB1rAoqnpIxG0jY3PdG7J2eTyzhNMraPchh39L6hrg+jNckRCO5EZT8xn1kXAf87syPlQp5TtOfpEmm8ojTg9lDGArf9MESv6/267ilPDTmESq0T5rD9T2+hpZ+f71AUfi1mMLtJtBSDzEI0Vn/C0Jk2lW43wv5CCp0Gk4KgtH8Pi5CiE4DrHkP46OFELDYUPpTFJavShq7KvKS5jyJK1XYKMLdz+8Be0+x9lHqcdiVwFiawIRA1XbBRmeTjLM4UOBpTbDyvayQUFggK3gDeURpti7d6N5roZnmx3S64LWnS4BSEHlOb5QWc6xg2GXZfqV9KPCUynyF/pyN8OyGv9+4zBYe2BacMz4tCjP/4xaHYAL7d8xfZ8YtmRFa5DKa5Gci37vSInzW2arOMe5p8xTnC464YThsVR9AyuupOgKa0aDItY2F6Ja+gK9EleLrgdGgOd32+MpFDprs47AaNHaHrZ5831BPYRTofBiizwvFvFBMiSx+/qXd/GFszTW8uz79NYXnkqzXIayfLLq91T7m96gDXCwuArteIcrLaHyKfcc+Sds/9K083IYGXUlUlVHdQ5q1R+g0+ijlUL5gxEifgwcQWXGG6JTux68GJTfDNEU5Ogzq7q10udbiX3YT6I37idboSFZEr+ga1w1NxXQYw8iyJPn5n3iEIeP3r8KIsqw7hF81/ownBZw76CacuYIj2x1qiyz6ZQcr3rYcSuPZ2oqCLb9qNs605z2mQAINfEpqId6OtkiGS2ZyVlegiSwlU48GBxb1qrO2sdQK79fARMbJIMi20zZH/r6rzaQj9Tu3xnab0HKOza7av6DWipcU1SOjjLGi8blmIB5YTkcUz9+bwXSVyoTAYhMcVDjGkLktqVoPhFMbviFRP
  template:
    metadata:
      name: botkube-communications
      namespace: default
    type: Opaque
