---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: botkube-communications
  namespace: default
spec:
  encryptedData:
    comm_config.yaml: AgAsBddySKNqq+rkBa3W7TMas+AFciw1VHB0xZjDqxhDK5zSgcVig4cKJBrEH3vzsmFtCNHibyElQKZYEmwyJ8JmYDX1NaXaWtgedC1WfBrYWRxTOmVukFJuSuZSX//eYX804wix36STrRxlPqVHOxuStOG1ncnKmZH5vAv2M4zL0cm53vhKqOciys3P7Or12lt+y5i+/AOP3FSRW1nzXWCzfo81JzoNjvIe7QTJNlVXE/i4nX5Usl2QzjbGxuSMq3kFzZV7O4IHdPcx3P7TQVcQHU4/td+rkJyVq7ENWcsZoYAcK1/Xj+2BBF28kSbNs8F3rYji7LTO/fr7ei/dQMCZQfYTTItnRzDa0yR1og4VTR0VQIou8z1VthXP7bVdTngufGMbmKruNX3ym0+J/azgi5uV/J4l4LNHPnafY2kENDRIh9LoP7Qa+uuFHhqIrJKEvhpAH6Y7tJk/Es30mqSqaA73aAZUD3XZ3ofE/v2boRJgjGX1xuqIEE7zJMqzIgrabafeDMoHt9L+Cn1Vskf1zg9dctYTl6/vKs3yvQ6LFdpHJ/uO1//7rGUxz2JGIFOpfxc0Ma9cBsFHBcIlg0wbrgdmK+MXGID+e09lxHVADTG8z/ZvygqN0m4ilRhIxIJRVScjq0RR7VGFJoFDHyhv0HJk2NuFaFF/B4FlnHptrAkJHTi9FBtCr9XMvGbKrkCpb+XPcoT0ARBASp1Rx7kDvh+31YjMIVgtl94oJie6IFPJcByFtRvFjRWkzW+/cyhI+RGjQYyfYI32op5FQFahYoA1NlOOlBX+c2TpubQ+7EaKEmSs3vhi8x2idyXkj8gO7RifMqJD7AVxuBLIvW+EEqZYCPbJNfYVfNwI8blAAkFAw7w2nLLUmaB5k2nqjmjIAumv1O4AOFA6S5SL68nIwcUijODnhdaCmEif5PQ72UEbWg9K9knxnt0Csdc+2ui/TgZwjZZ7lJ5VaKfGpGTu+qzxki8k0hEaAMz5qDtdhVbW3vUAICYLavF4cu145evXz81zGbFowip6rEOffEcAAi02La6uAebnBSMtiRedIHpZnuz6HMQiIXMv363XHmovxaJCwoEc5s/xX9TL0NhrU1RAh7y8T9qj4dTIxBzNP4w2YTk0jabAqec/YISHbGj3H7qXuHaIaFs2O1pbw9OBk4On6OOywAzwlc736IxaQ9VavIODLy3pB646YgX6w4u8Qy6r/XRJE+xIKJDEqHMsvX14G0sjoBmPRRSATQH+5pP+yYnFfJYG
  template:
    metadata:
      name: botkube-communications
      namespace: default
    type: Opaque
