apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellystat-backup
  namespace: jelly
  labels:
    app: jellystat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
