---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellystat-secret
  namespace: jelly
spec:
  encryptedData:
    JWT_SECRET: AgAZHsaZYU+EWSeMgsaviSAwwuc3A1+N7Z5P93nsDRoLyoQZ4gAYWtZvH3OBJHMUYf6R8L+awbo5IpoPe8UraNLEpLa+a6zjzrBOFEv/07pszluvQd2TciF0ejHCABGdBv66AJekI8Xnc9y54sDBJpdcPVchkpRYYqMQnFQt46P5SfWQLAns39lXgzrVf6koat8QP8dmJYrIKwPiRfP174hFyECk6Y8ldaaUMJNgzS/2XGGXxuaYAt492hP9uvQoirvpbyKuAhl3lRLJXHYm9gtwDy0VxIK3lfIUqAQ+1mSr3rlAH8eeT3tx2SdxukzEIqiYcMbxBxcsO/yU2lN7gSmAXoojynMziaoxb/1Ex5pKSuRy+/gMiTlqSkwFiHolGwtyyg94AHICUJuTWQdFlL2LyOcIImKIZ4W7sCIDYq7/xbwryOLho6c1GmHQSC/UFDSl1WaO2r97qiiXDtpm7qVj2GcoULqCvwRL3ipxSdJ/fcSiselsZv9BeV99inOvYKy04ykcyWkoMSS9mPK9SKng2JUkFVkdIB4HaO5ghVgUnX2P7M6uX6xBkaHwR2HA4qNy8gH/udte7SxluMaPghOHUmAyApXja3T/xnuJb1Qpoxr2ztXBH1meAALIASsxz3TAefzr78e4MKzhsuPDJAhPQCIvyBrrp5tjbNhPW4l0a4RV+zki/4+MPnEdVv+0o/APGRp2rV5iqZTs4VGeECvgGDp9TEZ0u6xcPzwzTh/lfaNnCoZOV/I57S1WJE1VfLo=
    POSTGRES_PASSWORD: AgBLYItoeEePSzPT8crL7eza397Lyeoh2QJqGCTnrKzoIjGYCQ4VK5uwyVcRtEZoo9jxm259O4dpJHHElLa/DpPwnnBEoyo2CaWDau9PJmlu9uQD9cJz+D3HM1WBu2Llrza5yPgo7WM2J6ZdWWul0QRbDV9Fwo6Bhyf2mZ3fGA1v6wvYglLG/N7P3oC4rekMpP+ixTN92OfLk4uSyt+X/FSvIM9znMaAGbjoJQUrmfBqUgq47XAfJ+dtFrz2yNg17oNZ6l2kZWXcU6jTdeUKnO29eGRL5zsnSrwxOFTNR5+pH1KQzfp4GEIHk5DwHldWfg9wFAUtKHOD8+72/uOCl3v5ZfPpWPQEjuaODhKbI8uQJj5VFg8UlGEeF10Q0+jANusTTJDVsjd/w86xcWdtJQSzdMavgjVhECRRNRL+fZ16/wEyWO+PGxb+iuQbTg07O4JV1NfKFFZ2DkTxLLD7TU3q5Yrqil2neZNNWsxonCHOr2nCvUjk8ZGMHGt9GUzzgXduzTpfdski1F+8Dw1lSAOQPMvD0IBmwexD/JFb+sxr65zbLUolY7dxKIxAAB6i5gFubuRXg1WF5Wd2nLi03cFH7SfsYAqRYpTopBU5vanQaEgP3vQbY1Db1mTk4I6zzD6yGn4bpQ64qwF/3wvOVU5y5QRRnGWfr/SblyWhrwmLs+64drk3d1wT8KcNDSlZcICfjo4odQV5GSzdgNhiz65tySAXgMshKj7Vhmn3b6MJ2w==
  template:
    metadata:
      name: jellystat-secret
      namespace: jelly
    type: Opaque
