# Tempo values for LGTM homelab deployment
# Single binary mode with local backend and multi-format trace ingestion

# Service account configuration
serviceAccount:
  create: true
  automount: true

# Tempo configuration
tempo:
  # Repository and tag
  repository: grafana/tempo
  tag: "2.3.1"
  pullPolicy: IfNotPresent
  
  # Resources for homelab environment
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  
  # Security context
  securityContext:
    readOnlyRootFilesystem: true
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
  
  # Readiness and liveness probes
  readinessProbe:
    httpGet:
      path: /ready
      port: 3100
    initialDelaySeconds: 30
    timeoutSeconds: 1
  
  livenessProbe:
    httpGet:
      path: /ready
      port: 3100
    initialDelaySeconds: 30
    timeoutSeconds: 1

# Service configuration
service:
  type: ClusterIP
  port: 3100
  annotations: {}

# Persistence configuration
persistence:
  enabled: true
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce
  size: 10Gi

# Tempo configuration file
config: |
  multitenancy_enabled: false
  usage_report:
    reporting_enabled: true
  compactor:
    compaction:
      compaction_window: 1h
      max_compaction_objects: 1000000
      block_retention: 72h  # 3 days retention
      compacted_block_retention: 10m
  distributor:
    receivers:
      # Jaeger receivers
      jaeger:
        protocols:
          thrift_http:
            endpoint: 0.0.0.0:14268
          thrift_binary:
            endpoint: 0.0.0.0:6832
          thrift_compact:
            endpoint: 0.0.0.0:6831
          grpc:
            endpoint: 0.0.0.0:14250
      # Zipkin receiver
      zipkin:
        endpoint: 0.0.0.0:9411
      # OpenTelemetry receivers
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      # OpenCensus receiver
      opencensus:
        endpoint: 0.0.0.0:55678
  ingester:
    max_block_duration: 5m
  server:
    http_listen_port: 3100
    log_level: info
  storage:
    trace:
      backend: local
      wal:
        path: /var/tempo/wal
      local:
        path: /var/tempo/blocks
      pool:
        max_workers: 100
        queue_depth: 10000
  querier:
    frontend_worker:
      frontend_address: tempo-query-frontend:9095
  query_frontend:
    search:
      duration_slo: 5s
      throughput_bytes_slo: 1.073741824e+09
    trace_by_id:
      duration_slo: 5s

# Service monitor for Prometheus scraping
serviceMonitor:
  enabled: true
  interval: 60s
  scrapeTimeout: 10s
  labels:
    release: kube-prometheus-stack
  annotations: {}

# Prometheus rules for Tempo alerting
prometheusRule:
  enabled: true
  groups:
    - name: tempo
      rules:
        - alert: TempoRequestLatency
          expr: histogram_quantile(0.99, sum(rate(tempo_request_duration_seconds_bucket[5m])) by (le)) > 3
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: Tempo request latency high
            description: "Tempo {{ $labels.instance }} has a 99th percentile latency of {{ $value }} seconds for the last 15 minutes."
        
        - alert: TempoCompactionsFailing
          expr: increase(tempo_compaction_errors_total[1h]) > 0
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: Tempo compactions failing
            description: "Tempo {{ $labels.instance }} has {{ $value }} compaction failures in the last hour."

# Additional ports for multi-format ingestion
ports:
  # Tempo internal
  - name: http
    port: 3100
    protocol: TCP
    targetPort: 3100
  
  # OpenTelemetry gRPC
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  
  # OpenTelemetry HTTP
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  
  # Jaeger Thrift compact
  - name: jaeger-thrift-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  
  # Jaeger Thrift binary
  - name: jaeger-thrift-binary
    port: 6832
    protocol: UDP
    targetPort: 6832
  
  # Jaeger gRPC
  - name: jaeger-grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  
  # Jaeger HTTP
  - name: jaeger-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  
  # Zipkin
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  
  # OpenCensus
  - name: opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678

# Pod disruption budget for availability
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Horizontal Pod Autoscaler (disabled for homelab)
autoscaling:
  enabled: false

# Node selector for scheduling
nodeSelector: {}

# Tolerations for scheduling
tolerations: []

# Affinity rules for scheduling
affinity: {}

# Extra environment variables
env: []

# Extra volumes
extraVolumes: []

# Extra volume mounts
extraVolumeMounts: []

# Extra containers
extraContainers: []

# Init containers
initContainers: []

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Deployment strategy
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

# Security context for the pod
podSecurityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

# Network policy (disabled by default)
networkPolicy:
  enabled: false

# Priority class
priorityClassName: ""

# Topology spread constraints
topologySpreadConstraints: []

# Termination grace period
terminationGracePeriodSeconds: 30

# DNS policy
dnsPolicy: ClusterFirst

# DNS config
dnsConfig: {}

# Host aliases
hostAliases: []

# Enable trace discovery for Grafana
traceDiscovery:
  enabled: true