apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyseerr-pv
  labels:
    app: jellyseerr
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.101
    path: /volume1/kube/jelly/jellyseerr-pvc
  claimRef:
    name: jellyseerr-pvc
    namespace: jelly