apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: jelly
  labels:
    app: jellyseerr
spec:
  type: LoadBalancer
  ports:
  - port: 5055
    targetPort: 5055
    protocol: TCP
    name: http
  selector:
    app: jellyseerr