apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: homelab-complete-backup
  namespace: velero
spec:
  schedule: "0 2 * * *" # Daily at 2 AM
  template:
    excludedNamespaces:
      - kube-system # Core K8s components (kubelet, kube-proxy, CNI)
      - kube-public # Public cluster info (gets recreated)
      - kube-node-lease # Node heartbeat data (ephemeral)
    includedClusterScopedResources:
      - "*" # Include all cluster-scoped resources
    excludedClusterScopedResources:
      - nodes # Physical node info (recreated by cluster)
      - events # Ephemeral event data (not needed)
      - componentstatuses # Runtime component status (recreated)
      - csidrivers # Storage drivers (reinstalled with storage)
      - csinodes # Node-specific CSI data (recreated)
    snapshotVolumes: true
    storageLocation: default
