apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-prometheus-stack-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-grafana
  resources:
    requests:
      storage: 10Gi