apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-loki
  resources:
    requests:
      storage: 30Gi