apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: my-jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: my-jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app.kubernetes.io/instance: my-jellyfin
    spec:
      containers:
        - name: jellyfin
          securityContext: {}
          image: "jellyfin/jellyfin:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Asia/Singapore"
            - name: JELLYFIN_CONFIG_DIR
              value: "/config"
            - name: JELLYFIN_CACHE_DIR
              value: "/cache"
            - name: JELLYFIN_DATA_DIR
              value: "/data"
            - name: JELLYFIN_LOG_DIR
              value: "/logs"
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /cache
            - name: data
              mountPath: /data
            - name: logs
              mountPath: /logs
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
        - name: cache
          persistentVolumeClaim:
            claimName: jellyfin-cache-pvc
        - name: data
          persistentVolumeClaim:
            claimName: jellyfin-data-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: jellyfin-logs-pvc
