apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: my-jellyfin
spec:
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce # Suitable for a single pod deployment
  resources:
    requests:
      storage: 10Gi # Adjust as needed

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-pvc
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: my-jellyfin
spec:
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi # Adjust as needed

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data-pvc
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: my-jellyfin
spec:
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi # Adjust significantly based on your media library size

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-logs-pvc
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: my-jellyfin
spec:
  storageClassName: synology-iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust as needed
