apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: my-jellyfin
spec:
  type: LoadBalancer 
  ports:
    - port: 8096
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: my-jellyfin
