# Kubernetes Descheduler - Homelab Configuration
# Runs 3 times daily to optimize pod placement across nodes

# Run as CronJob with 3x daily schedule
kind: CronJob

# Schedule: Every 2 hours for more frequent rebalancing
schedule: "0 */2 * * *"

# Keep minimal job history
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1

# Image configuration
image:
  repository: registry.k8s.io/descheduler/descheduler
  pullPolicy: IfNotPresent

# Resource limits - minimal for homelab
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

# Priority for scheduling
priorityClassName: system-cluster-critical

# Create RBAC resources
rbac:
  create: true

# Service account
serviceAccount:
  create: true

# Command options
cmdOptions:
  # Set to true to test without actually evicting pods
  dry-run: false
  # Logging verbosity (0-5) - increased for better debugging
  v: 4

# Descheduler Policy Configuration
deschedulerPolicy:
  # Profile for homelab optimization
  profiles:
    - name: HomelabProfile
      pluginConfig:
        # Default evictor configuration
        - name: "DefaultEvictor"
          args:
            evictSystemCriticalPods: false
            evictFailedBarePods: true
            evictLocalStoragePods: false
            # Allow eviction of PVC pods for better distribution
            ignorePvcPods: false
            nodeFit: true
            # Increased pod age to 30 minutes for stability
            minPodAge: "30m"
        
        # High node utilization - evict from overloaded nodes
        - name: "HighNodeUtilization"
          args:
            # Evict from nodes above these thresholds
            thresholds:
              cpu: 70
              memory: 70
              pods: 65
            # Exclude critical namespaces
            evictableNamespaces:
              exclude:
                - "kube-system"
                - "synology-csi"
                - "metallb"
                - "cert-manager"
        
        # Spread duplicate pods across nodes
        - name: "RemoveDuplicates"
          args:
            # Don't evict pods managed by these controllers
            excludeOwnerKinds:
              - "DaemonSet"
            namespaces:
              exclude:
                - "kube-system"
        
        # Remove old pods to allow rescheduling
        - name: "PodLifeTime"
          args:
            # 7 days in seconds
            maxPodLifeTimeSeconds: 604800
            namespaces:
              exclude:
                - "kube-system"
                - "synology-csi"
                - "metallb"
                - "cert-manager"
        
        # Remove pods with too many restarts
        - name: "RemovePodsHavingTooManyRestarts"
          args:
            podRestartThreshold: 100
            includingInitContainers: true
        
        # Remove failed pods
        - name: "RemoveFailedPods"
          args:
            # Only remove pods that have been failed for at least 1 hour
            minPodLifetimeSeconds: 3600
            includingInitContainers: true
            excludeOwnerKinds:
              - "Job"
              - "CronJob"
        
        # Remove pods violating node affinity
        - name: "RemovePodsViolatingNodeAffinity"
          args:
            nodeAffinityType:
              - "requiredDuringSchedulingIgnoredDuringExecution"
      
      plugins:
        # Enable deschedule plugins
        deschedule:
          enabled:
            - "RemovePodsHavingTooManyRestarts"
            - "RemoveFailedPods"
            - "PodLifeTime"
            - "RemovePodsViolatingNodeAffinity"
        # Enable balance plugins
        balance:
          enabled:
            - "HighNodeUtilization"
            - "RemoveDuplicates"