# Traefik Helm Chart Values - NPM Replacement
# Provides: Auto SSL via Let's Encrypt, Web Dashboard, Multiple DNS Providers

# High Availability Deployment
deployment:
  kind: Deployment
  replicas: 2  # HA setup - one pod can fail without service interruption

# Entry Points - Where Traefik listens for traffic
ports:
  web:
    port: 8000      # Internal container port
    expose: true
    exposedPort: 80 # External HTTP port
    redirectTo: websecure  # Auto-redirect HTTP → HTTPS (like NPM)
  websecure:
    port: 8443      # Internal container port  
    expose: true
    exposedPort: 443 # External HTTPS port
    tls:
      enabled: true  # Enable SSL/TLS termination

# MetalLB LoadBalancer Service - Gets external IP like arr-stack services
service:
  type: LoadBalancer
  externalTrafficPolicy: Local  # Preserves real client IP addresses (important for logs/security)
  loadBalancerIP: "192.168.10.11"  # Request specific IP from MetalLB pool

# Let's Encrypt Certificate Resolvers - Auto SSL like NPM
certificatesResolvers:
  # For DuckDNS domains (*.duckdns.org)
  duckdns:
    acme:
      email: your-email@example.com  # CHANGE THIS to your email
      storage: /data/acme.json       # Certificate storage location
      dnsChallenge:
        provider: duckdns
        delayBeforeCheck: 60         # DNS propagation wait time
        resolvers:
          - "1.1.1.1:53"            # Cloudflare DNS for reliability
          - "8.8.8.8:53"            # Google DNS backup
  
  # For Cloudflare domains (your custom domains)
  cloudflare:
    acme:
      email: your-email@example.com  # CHANGE THIS to your email
      storage: /data/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 30         # Cloudflare DNS is usually faster
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

# Persistent Storage for Certificates - Critical for Let's Encrypt
persistence:
  enabled: true
  size: 128Mi
  path: /data
  # Uses default storage class from your cluster

# Dashboard Configuration - Web interface like NPM
dashboard:
  enabled: true
# We'll create a secure IngressRoute separately for dashboard access

# DNS Provider Environment Variables - API credentials for Let's Encrypt
env:
  # DuckDNS API Token
  - name: DUCKDNS_TOKEN
    valueFrom:
      secretKeyRef:
        name: dns-secrets
        key: duckdns-token
  
  # Cloudflare API Token (NOT Global API Key - use scoped token)
  - name: CF_DNS_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: dns-secrets
        key: cloudflare-token

# Logging Configuration
logs:
  general:
    level: INFO  # Change to DEBUG for troubleshooting
  access:
    enabled: true  # Access logs for monitoring

# Prometheus Metrics - Optional monitoring integration
metrics:
  prometheus:
    enabled: true
    # If you have Prometheus Operator, this will auto-discover

# Resource Limits - Appropriate for homelab environment
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "750m"     # Generous for SSL processing
    memory: "250Mi"

# Security: Disable unnecessary endpoints
ping:
  enabled: false    # Disable public ping endpoint

# Additional Arguments - Fine-tune Traefik behavior
additionalArguments:
  # Enable more detailed logs for certificate resolver
  - "--log.level=INFO"
  # Increase timeout for slow DNS providers
  - "--certificatesresolvers.duckdns.acme.dnschallenge.delaybeforecheck=60"
  - "--certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=30"