apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerr-data
  namespace: arr-stack
  labels:
    app: maintainerr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synostorage
  resources:
    requests:
      storage: 1Gi
