apiVersion: v1
kind: Service
metadata:
  name: maintainerr-service
  namespace: arr-stack
  labels:
    app: maintainerr
spec:
  selector:
    app: maintainerr
  type: LoadBalancer
  ports:
  - name: webui
    protocol: TCP
    port: 6246
    targetPort: webui
