apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifiarr
  namespace: arr-stack
  labels:
    app: notifiarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifiarr
  template:
    metadata:
      labels:
        app: notifiarr
    spec:
      containers:
      - name: notifiarr
        image: golift/notifiarr:0.9.2
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Singapore"

        ports:
        - containerPort: 5454
          name: http
        volumeMounts:
        - name: notifiarr-config
          mountPath: /config
        - name: host-machine-id
          mountPath: /etc/machine-id
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 5454
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 5454
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"

      volumes:
      - name: notifiarr-config
        persistentVolumeClaim:
          claimName: notifiarr-config
      - name: host-machine-id
        hostPath:
          path: /etc/machine-id
          type: File