apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: arr-stack
  labels:
    app: nzbget
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: lscr.io/linuxserver/nzbget:25.2.20250815
        imagePullPolicy: IfNotPresent
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Singapore"
        ports:
        - containerPort: 6789
          name: nzbget-webui
        volumeMounts:
        - name: nzbget-config
          mountPath: /config
        - name: nfs-nas
          mountPath: /NAS
        livenessProbe:
          tcpSocket:
            port: 6789
          initialDelaySeconds: 120
          periodSeconds: 60
      volumes:
      - name: nzbget-config
        persistentVolumeClaim:
          claimName: nzbget-config
      - name: nfs-nas
        nfs:
          server: 192.168.10.101
          path: /volume1/NAS