apiVersion: v1
kind: Service
metadata:
  name: nzbget-service
  namespace: arr-stack
  labels:
    app: nzbget
spec:
  selector:
    app: nzbget
  type: LoadBalancer
  loadBalancerIP: 192.168.10.21
  ports:
  - name: webui
    protocol: TCP
    port: 6789
    targetPort: nzbget-webui