apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluetun-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""  # Empty to bind to specific PV
  volumeName: pv-gluetun-config  # Bind to specific PV
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-qbittorrent-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-nzbget-config
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-prowlarr-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-radarr-config
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr2-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-radarr2-config
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-sonarr-config
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr2-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-sonarr2-config
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-bazarr-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr2-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-bazarr2-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifiarr-config
  namespace: arr-stack
  labels:
    velero.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-notifiarr-config
  resources:
    requests:
      storage: 2Gi