---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: arr-stack
spec:
  selector:
    app: sonarr
  ports:
    - port: 8989
      targetPort: 8989
      name: http
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr2-service
  namespace: arr-stack
spec:
  selector:
    app: sonarr2
  ports:
    - port: 8989
      targetPort: 8989
      name: http
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: arr-stack
spec:
  selector:
    app: radarr
  ports:
    - port: 7878
      targetPort: 7878
      name: http
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: radarr2-service
  namespace: arr-stack
spec:
  selector:
    app: radarr2
  ports:
    - port: 7878
      targetPort: 7878
      name: http
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr-service
  namespace: arr-stack
spec:
  selector:
    app: bazarr
  ports:
    - port: 6767
      targetPort: 6767
      name: http
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr2-service
  namespace: arr-stack
spec:
  selector:
    app: bazarr2
  ports:
    - port: 6767
      targetPort: 6767
      name: http
  type: LoadBalancer

