apiVersion: v1
kind: Service
metadata:
  name: vpn-group-service
  namespace: arr-stack
spec:
  type: LoadBalancer
  selector:
    app: vpn-group
  ports:
  - name: qbittorrent
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: qb-torrent
    port: 6881
    targetPort: 6881
    protocol: TCP
  - name: nzbget
    port: 6789
    targetPort: 6789
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  namespace: arr-stack
spec:
  type: LoadBalancer
  selector:
    app: prowlarr
  ports:
  - name: http
    port: 9696
    targetPort: 9696
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: arr-stack
spec:
  type: LoadBalancer
  selector:
    app: radarr
  ports:
  - name: radarr
    port: 7878
    targetPort: 7878
    protocol: TCP
  - name: radarr2
    port: 7879
    targetPort: 7879
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: arr-stack
spec:
  type: LoadBalancer
  selector:
    app: sonarr
  ports:
  - name: sonarr
    port: 8989
    targetPort: 8989
    protocol: TCP
  - name: sonarr2
    port: 8990
    targetPort: 8990
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr-service
  namespace: arr-stack
spec:
  type: LoadBalancer
  selector:
    app: bazarr
  ports:
  - name: bazarr
    port: 6767
    targetPort: 6767
    protocol: TCP
  - name: bazarr2
    port: 6768
    targetPort: 6768
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: notifiarr-service
  namespace: arr-stack
spec:
  type: LoadBalancer
  selector:
    app: notifiarr
  ports:
  - name: http
    port: 5454
    targetPort: 5454
    protocol: TCP