apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-test-host
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-test-host
  template:
    metadata:
      labels:
        app: vpn-test-host
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:v3.39.0
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "expressvpn"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: arr-stack-secrets
              key: expressvpn-username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: arr-stack-secrets
              key: expressvpn-password
        - name: SERVER_COUNTRIES
          value: "Singapore"
        - name: TZ
          value: "Asia/Singapore"
        - name: LOG_LEVEL
          value: "debug"
        - name: HTTP_CONTROL_SERVER_PORT
          value: "8001"
        - name: HEALTH_SERVER_ADDRESS
          value: "127.0.0.1:9998"
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-net-tun
          mountPath: /dev/net/tun
      volumes:
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice