apiVersion: v1
kind: Service
metadata:
  name: vpn-group-service
  namespace: arr-stack
  labels:
    app: vpn-group
spec:
  selector:
    app: vpn-group
  type: LoadBalancer  # Use LoadBalancer for external access
  loadBalancerIP: 192.168.10.20
  ports:
  - name: qbittorrent-webui
    protocol: TCP
    port: 8080
    targetPort: qb-webui
  - name: nzbget-webui
    protocol: TCP
    port: 6789
    targetPort: nzbget-webui
  - name: qbittorrent-torrent
    protocol: TCP
    port: 6881
    targetPort: qb-torrent
    # Note: This port may need UDP as well for torrent traffic
  - name: qbittorrent-torrent-udp
    protocol: UDP
    port: 6881
    targetPort: qb-torrent