apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-test-debug
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-test-debug
  template:
    metadata:
      labels:
        app: vpn-test-debug
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:v3.39.0
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "expressvpn"
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: arr-stack-secrets
              key: expressvpn-username
        - name: OPENVPN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: arr-stack-secrets
              key: expressvpn-password
        - name: SERVER_COUNTRIES
          value: "Singapore"
        # Debug firewall commands
        - name: FIREWALL_DEBUG
          value: "on"
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        - name: TZ
          value: "Asia/Singapore"
        - name: LOG_LEVEL
          value: "debug"
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev-net-tun
          mountPath: /dev/net/tun
      volumes:
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice