apiVersion: v1
kind: ConfigMap
metadata:
  name: openvpn-config
  namespace: arr-stack
data:
  expressvpn.ovpn: |
    client
    dev tun
    proto udp
    remote singapore-3-ca-version-2.expressnetw.com 1195
    remote singapore-4-ca-version-2.expressnetw.com 1195
    remote singapore-5-ca-version-2.expressnetw.com 1195
    remote singapore-6-ca-version-2.expressnetw.com 1195
    remote singapore-ca-version-2.expressnetw.com 1195
    remote-random
    resolv-retry infinite
    nobind
    persist-key
    persist-tun
    persist-remote-ip
    cipher AES-256-CBC
    auth SHA512
    verb 3
    remote-cert-tls server
    auth-user-pass /config/auth.txt
    reneg-sec 0
    disable-occ
    fast-io
    
    ca /config/ca.crt
    cert /config/client.crt
    key /config/client.key
    tls-auth /config/ta.key 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-openvpn
  namespace: arr-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpn-openvpn
  template:
    metadata:
      labels:
        app: vpn-openvpn
    spec:
      containers:
      - name: openvpn
        image: dperson/openvpn-client:latest
        env:
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
        - name: dev-net-tun
          mountPath: /dev/net/tun
        - name: openvpn-config
          mountPath: /vpn
        - name: auth-secret
          mountPath: /config
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:4.6.7
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Singapore"
        - name: WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: qb-webui
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: nfs-nas
          mountPath: /NAS
      - name: nzbget
        image: lscr.io/linuxserver/nzbget:latest
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Singapore"
        ports:
        - containerPort: 6789
          name: nzbget-webui
        volumeMounts:
        - name: nzbget-config
          mountPath: /config
        - name: nfs-nas
          mountPath: /NAS
      volumes:
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      - name: openvpn-config
        configMap:
          name: openvpn-config
      - name: auth-secret
        secret:
          secretName: expressvpn-auth
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: nzbget-config
        persistentVolumeClaim:
          claimName: nzbget-config
      - name: nfs-nas
        nfs:
          server: 192.168.10.101
          path: /volume1/NAS