---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellystat-user-secret
  namespace: default
spec:
  encryptedData:
    password: AgBxmAxxxNlqV7UJSQ/U16DyOxwLcni4ve+fa60gIfe8pdHeC2UJ1hPnG+z5dIYF6mqWWkUa6qeeYLyMsD0VAPu+uBHLnKuotehyvLCtLJRa4dsoQuXOwCP5bgJp/GMchf1tcQg07yqQDxbeEjxJiaG2X2QELcNvJNcVWeFXunWz9c7mMortGLPy71C7s7lZ3QESGNzgsrIssliEEvqaLIMs4Vu36RXqkNTFtYyWL2pyHIya0mKTcodJsZApM5E9NMyhC6aRVEbt4wqNixfeSylrwTA6JwywID4SK47xMGl7ZXXYoa2wMYB4uSKrD//8RnBSSfL6Xwtfi0bBVpNxm+Dgm1XKDhnS9Fb37eYtjrwkefvorFP1GqnBs680DNWJVev84aSYTLKHeiY+bYykSKFA2UTOt7amgmqOVgZd9GpfYlpDCl9Op5K1eSJs3MxJK5omCphN8Tw4uA6XaZSJHnewUTeZWPBtttLEuVuZolfFRNM3ftLWdMxj8a365yyp0AiWzmC4eWJK0KHKnFkpfbBdySJjL9gl3rgxB+l+fGgkAzWRkTsTFXYmZfKRTqiWArRg6Pgad3pVAIyU5iVkNu503hxcguXLazcWjGvKzGHMIYeR0QNFGSEsoAgWXMUx2x5ZvXuc28mKLkDvFTgiJa2vCQNFoxqsm3KGngUEiJfrC4oiiXvpD/WheOdOb7LQ6ejgbvyRKhXaqeTUJFlQUrYozIOeMfrhoaF5WuOfzFdjEw==
    username: AgBtB9F0ChcPhJZosPd89cCAykDijizTA4rkWUsZRvTXO+d49R4h6mKCabyw13nDXMVI2FAd9h02T0Nytl8Dz4l9H4ltnGGq1YhFkiYXvhEa1FcD2oOLWGb0AcfIS9RHuGfz5iSYGZNJHcQuFikVFZWP0KBR5IrMU0L+7fuk5bjJP7dEwTXxCQqIRXysmjmbDXy5cXRcu2ty+PHF+hfsr2y3R7lC3/blszI0rhSkrALKl6KNBBR7WKPZWrIi1t8vebLYNEOFypwtpHjZPNffh/mCW8EjU7JzQZT+JnKqMxHM/yopn3wf3Fa+bMw+etVLWJ52VF+QVun7nJLhZLxtqgNlh/+t+fyo+hMjqRpsX/la8UiZvi3NTvyf4VAo0K8WV60p6NX8Tf80Z+NXXSZ5EV1KhNXaD+62dMfwloNYz01QNBlyQp/yjVEs3pJk2PMcwFt9jFQRF0g3Kj+fqRvqPWb5s3ItUcJyCLzFCenkpv/44/7bA3cgQQZJ6xcu1ommjK6u0RGWH+fQj/F1JY4XWbmut7pO8A4lvmy280+5BKMjw64HlVg1Ls3DHAPyr6IDg8NIkxRIOdN7/wcYhkQaMV9xQyk8a/rbKinUSTG1H0xmCXdtQAB2UUdUKJqzkLGxoD4mq0qefuaN7abj94xJiKm8baIZR9bAccmL09p+ZmOpCd82l4TEHeew9xXEPPO7AFD/tmw72XlcJGU=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: jellystat-user-secret
      namespace: default
    type: kubernetes.io/basic-auth
