apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-deployer-binding
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-deployer-permissions
subjects:
  - kind: ServiceAccount
    name: claudecode-sa
    namespace: default
