apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-permissions
rules:
- apiGroups: [""]
  resources: ["namespaces", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Global debugging permissions (read-only)
- apiGroups: [""]
  resources: ["endpoints", "events"]
  verbs: ["get", "list"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies", "ingresses"]
  verbs: ["get", "list"]
# Storage debugging
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments", "csinodes", "csidrivers"]
  verbs: ["get", "list"]
# Cilium resources (if using Cilium CNI)
- apiGroups: ["cilium.io"]
  resources: ["ciliumnetworkpolicies", "ciliumendpoints"]
  verbs: ["get", "list"]
# MetalLB resources
- apiGroups: ["metallb.io"]
  resources: ["ipaddresspools", "l2advertisements", "bgppeers"]
  verbs: ["get", "list"]
# Metrics
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
# Security and RBAC
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["get", "list"]
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["get", "list"]
# ConfigMaps in kube-system (for CNI debugging)
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["*"]
  verbs: ["get", "list"]
# GPU debugging permissions
- apiGroups: [""]
  resources: ["pods", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
# Traefik CRDs (traefik.io API group)
- apiGroups: ["traefik.io"]
  resources: ["ingressroutes", "middlewares", "ingressroutetcps", "ingressrouteudps", "tlsstores", "tlsoptions", "serverstransports", "traefikservices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Cert-manager resources
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "certificaterequests", "issuers", "clusterissuers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Cert-manager ACME resources
- apiGroups: ["acme.cert-manager.io"]
  resources: ["orders", "challenges"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ServiceAccounts
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list", "watch"]
# Descheduler CronJob read-only permissions
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list", "watch"]
# CloudNativePG (CNPG) resources
- apiGroups: ["postgresql.cnpg.io"]
  resources: ["clusters", "databases", "poolers", "backups", "scheduledbackups"]
  verbs: ["get", "list", "watch"]
# Velero backup and restore permissions
- apiGroups: ["velero.io"]
  resources: ["backups", "backupstoragelocations", "deletebackuprequests", "downloadrequests", "podvolumebackups", "podvolumerestores", "resticrepositories", "restores", "schedules", "serverstatusrequests", "volumesnapshotlocations", "backuprepositories", "datadownloads", "datauploads"]
  verbs: ["get", "list", "watch"]
# Velero backup status and progress monitoring
- apiGroups: ["velero.io"]
  resources: ["backups/status", "restores/status", "schedules/status", "downloadrequests/status", "serverstatusrequests/status"]
  verbs: ["get", "list", "watch"]
# Velero namespace - pod and log access for monitoring
# Note: ClusterRole grants cluster-wide permissions, namespace-specific access controlled via RoleBinding
- apiGroups: [""]
  resources: ["pods", "pods/log", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]