apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: global-permissions
rules:
- apiGroups: [""]
  resources: ["namespaces", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list"]