apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Image updater configuration
spec:
  project: default
  source:
    repoURL: https://github.com/Gauransh-Homelab/Homelab.git
    targetRevision: main
    path: kubernetes/jellyseerr
  destination:
    server: https://kubernetes.default.svc
    namespace: jelly
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m