apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: ai-stuff
type: Opaque
stringData:
  HOST: "0.0.0.0"
  PORT: "3080"
  MONGO_URI: "mongodb://librechat-mongodb:27017/LibreChat"
  DOMAIN_CLIENT: "https://your-domain-here.com"
  DOMAIN_SERVER: "https://your-domain-here.com"
  NO_INDEX: "true"
  CONSOLE_JSON: "false"
  DEBUG_LOGGING: "true"
  DEBUG_CONSOLE: "false"
  PROXY: ""
  PERPLEXITY_API_KEY: "your-perplexity-api-key-here"
  ANTHROPIC_API_KEY: "your-anthropic-api-key-here"
  BINGAI_TOKEN: "user_provided"
  GOOGLE_KEY: "your-google-api-key-here"
  GOOGLE_MODELS: "gemini-2.5-pro-preview-05-06,gemini-2.0-flash-exp,gemini-2.0-flash-thinking-exp-1219,gemini-exp-1121,gemini-exp-1114,gemini-1.5-flash-latest,gemini-1.0-pro,gemini-1.0-pro-001,gemini-1.0-pro-latest,gemini-1.0-pro-vision-latest,gemini-1.5-pro-latest,gemini-pro,gemini-pro-vision"
  OPENAI_API_KEY: "your-openai-api-key-here"
  DEBUG_OPENAI: "false"
  ASSISTANTS_API_KEY: "user_provided"
  DEBUG_PLUGINS: "true"
  CREDS_KEY: "your-creds-key-here"
  CREDS_IV: "your-creds-iv-here"
  AZURE_AI_SEARCH_SERVICE_ENDPOINT: ""
  AZURE_AI_SEARCH_INDEX_NAME: ""
  AZURE_AI_SEARCH_API_KEY: ""
  AZURE_AI_SEARCH_API_VERSION: ""
  AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE: ""
  AZURE_AI_SEARCH_SEARCH_OPTION_TOP: ""
  AZURE_AI_SEARCH_SEARCH_OPTION_SELECT: ""
  GOOGLE_SEARCH_API_KEY: "your-google-search-api-key-here"
  GOOGLE_CSE_ID: "your-google-cse-id-here"
  SERPAPI_API_KEY: ""
  SD_WEBUI_URL: "http://host.docker.internal:7860"
  TAVILY_API_KEY: ""
  TRAVERSAAL_API_KEY: ""
  WOLFRAM_APP_ID: ""
  ZAPIER_NLA_API_KEY: ""
  SEARCH: "true"
  MEILI_NO_ANALYTICS: "true"
  MEILI_HOST: "http://librechat-meilisearch:7700"
  MEILI_MASTER_KEY: "your-meili-master-key-here"
  STT_API_KEY: ""
  TTS_API_KEY: ""
  RAG_API_URL: "http://host.docker.internal:8000"
  RAG_OPENAI_API_KEY: "your-openai-api-key-here"
  OPENAI_MODERATION: "false"
  OPENAI_MODERATION_API_KEY: ""
  BAN_VIOLATIONS: "true"
  BAN_DURATION: "7200000"
  BAN_INTERVAL: "20"
  LOGIN_VIOLATION_SCORE: "1"
  REGISTRATION_VIOLATION_SCORE: "1"
  CONCURRENT_VIOLATION_SCORE: "1"
  MESSAGE_VIOLATION_SCORE: "1"
  NON_BROWSER_VIOLATION_SCORE: "20"
  LOGIN_MAX: "7"
  LOGIN_WINDOW: "5"
  REGISTER_MAX: "5"
  REGISTER_WINDOW: "60"
  LIMIT_CONCURRENT_MESSAGES: "true"
  CONCURRENT_MESSAGE_MAX: "2"
  LIMIT_MESSAGE_IP: "true"
  MESSAGE_IP_MAX: "40"
  MESSAGE_IP_WINDOW: "1"
  LIMIT_MESSAGE_USER: "false"
  MESSAGE_USER_MAX: "40"
  MESSAGE_USER_WINDOW: "1"
  ILLEGAL_MODEL_REQ_SCORE: "5"
  CHECK_BALANCE: "false"
  ALLOW_EMAIL_LOGIN: "false"
  ALLOW_REGISTRATION: "false"
  ALLOW_SOCIAL_LOGIN: "true"
  ALLOW_SOCIAL_REGISTRATION: "false"
  ALLOW_PASSWORD_RESET: "false"
  ALLOW_UNVERIFIED_EMAIL_LOGIN: "false"
  SESSION_EXPIRY: "900000"
  REFRESH_TOKEN_EXPIRY: "604800000"
  JWT_SECRET: "your-jwt-secret-here"
  JWT_REFRESH_SECRET: "your-jwt-refresh-secret-here"
  DISCORD_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""
  DISCORD_CALLBACK_URL: "/oauth/discord/callback"
  FACEBOOK_CLIENT_ID: ""
  FACEBOOK_CLIENT_SECRET: ""
  FACEBOOK_CALLBACK_URL: "/oauth/facebook/callback"
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
  GITHUB_CALLBACK_URL: "/oauth/github/callback"
  GOOGLE_CLIENT_ID: "your-google-client-id-here"
  GOOGLE_CLIENT_SECRET: "your-google-client-secret-here"
  GOOGLE_CALLBACK_URL: "/oauth/google/callback"
  OPENID_CLIENT_ID: ""
  OPENID_CLIENT_SECRET: ""
  OPENID_ISSUER: ""
  OPENID_SESSION_SECRET: ""
  OPENID_SCOPE: "openid profile email"
  OPENID_CALLBACK_URL: "/oauth/openid/callback"
  OPENID_REQUIRED_ROLE: ""
  OPENID_REQUIRED_ROLE_TOKEN_KIND: ""
  OPENID_REQUIRED_ROLE_PARAMETER_PATH: ""
  OPENID_USERNAME_CLAIM: ""
  OPENID_NAME_CLAIM: ""
  OPENID_BUTTON_LABEL: ""
  OPENID_IMAGE_URL: ""
  LDAP_URL: ""
  LDAP_BIND_DN: ""
  LDAP_BIND_CREDENTIALS: ""
  LDAP_USER_SEARCH_BASE: ""
  LDAP_SEARCH_FILTER: "mail={{username}}"
  LDAP_CA_CERT_PATH: ""
  EMAIL_SERVICE: ""
  EMAIL_HOST: ""
  EMAIL_PORT: "25"
  EMAIL_ENCRYPTION: ""
  EMAIL_ENCRYPTION_HOSTNAME: ""
  EMAIL_ALLOW_SELFSIGNED: ""
  EMAIL_USERNAME: ""
  EMAIL_PASSWORD: ""
  EMAIL_FROM_NAME: ""
  EMAIL_FROM: "noreply@librechat.ai"
  FIREBASE_API_KEY: ""
  FIREBASE_AUTH_DOMAIN: ""
  FIREBASE_PROJECT_ID: ""
  FIREBASE_STORAGE_BUCKET: ""
  FIREBASE_MESSAGING_SENDER_ID: ""
  FIREBASE_APP_ID: ""
  ALLOW_SHARED_LINKS: "true"
  ALLOW_SHARED_LINKS_PUBLIC: "true"
  APP_TITLE: "LibreChat"
  HELP_AND_FAQ_URL: "https://librechat.ai"