apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jelly # Adjust if using a different namespace
  labels:
    app: jellyfin
spec:
  replicas: 1
  strategy:
    type: Recreate # Ensures old pod stops before new one starts, good for stateful apps
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      annotations:
        backup.velero.io/backup-volumes: config-volume,data-volume
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - proxmox
      securityContext:
        supplementalGroups:
          - 44 # video group for GPU access
          - 104 # render group for GPU access
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin:10.10.7
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
              gpu.intel.com/i915: "1"
            requests:
              memory: "2Gi"
              cpu: "500m"
              gpu.intel.com/i915: "1"
          env:
            - name: JELLYFIN_CACHE_DIR
              value: "/var/cache/jellyfin"
            - name: JELLYFIN_CONFIG_DIR
              value: "/etc/jellyfin"
            - name: JELLYFIN_DATA_DIR
              value: "/var/lib/jellyfin"
            - name: JELLYFIN_LOG_DIR
              value: "/var/log/jellyfin"
            - name: TZ
              value: "Asia/Singapore"
          ports:
            - name: http
              containerPort: 8096 # Default Jellyfin HTTP port
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/jellyfin # Matches JELLYFIN_CONFIG_DIR
            - name: cache-volume
              mountPath: /var/cache/jellyfin # Matches JELLYFIN_CACHE_DIR
            - name: data-volume
              mountPath: /var/lib/jellyfin # Matches JELLYFIN_DATA_DIR
            - name: log-volume
              mountPath: /var/log/jellyfin # Matches JELLYFIN_LOG_DIR
            - name: media
              mountPath: /NAS
            - name: dri
              mountPath: /dev/dri

      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: jellyfin-config # Replace with your existing PVC name for config
        - name: cache-volume
          persistentVolumeClaim:
            claimName: jellyfin-cache # Replace with your existing PVC name for cache
        - name: data-volume
          persistentVolumeClaim:
            claimName: jellyfin-data # Replace with your existing PVC name for data
        - name: log-volume
          persistentVolumeClaim:
            claimName: jellyfin-log # Replace with your existing PVC name for logs
        - name: media
          nfs:
            server: 192.168.10.101
            path: /volume1/NAS
            readOnly: false
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
