apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jelly # Adjust if using a different namespace
spec:
  type: LoadBalancer # Or NodePort, or ClusterIP (if using Ingress)
  selector:
    app: jellyfin # This must match the labels on your Pods/Deployment
  ports:
    - name: http
      protocol: TCP
      port: 8096       # Port the service will listen on
      targetPort: 8096

